Repository etalab/admin_api_entreprise, pull requests merged in 2023-05, with the labels that each got.

#1026 Bug affichage panneau : Ajoute la condition manquante
  app/views/api_particulier/endpoints/show.html.erb
Labels: urgent

#1036 Fix/sentry mail 2
  app/interactors/datapass_webhook/schedule_authorization_request_emails.rb
  spec/interactors/datapass_webhook/schedule_authorization_request_emails_spec.rb
  spec/jobs/schedule_authorization_request_mailjet_email_job_spec.rb
Labels: 🐛 bug

#1041 Fix/contacts
  app/helpers/user_sessions_helper.rb
  app/interactors/datapass_webhook/schedule_authorization_request_emails.rb
  app/jobs/schedule_authorization_request_mailjet_email_job.rb
  app/views/api_entreprise/tokens/_token.html.erb
  spec/features/api_entreprise/token_contacts_spec.rb
  spec/features/api_entreprise/token_details_spec.rb
  spec/jobs/schedule_authorization_request_mailjet_email_job_spec.rb
  spec/organizers/datapass_webhook/api_entreprise_spec.rb
Labels: 🐛 bug

#775 [Fiche métier] Api probtp doc
  config/endpoints/api_entreprise/17_probtp_conformites_cotisations_retraite.yml
Labels: documentation

#1055 [API scolarité] Documente les années scolaires disponibles
  config/endpoints/api_particulier/education_nationale_statut_eleve.yml
Labels: documentation
